// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymgdrvdfresfjtyaxaio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZ2RydmRmcmVzZmp0eWF4YWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjMwMjgsImV4cCI6MjA1OTkzOTAyOH0.5Ttuc-U8CEUlIi-7ZpCR21QcymZn1CrcCsjH2IYSNhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);